default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=2000']
    -   id: end-of-file-fixer
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: requirements-txt-fixer

    # Changes tabs to spaces
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
    -   id: remove-tabs

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.2.0
    hooks:
    -   id: pretty-format-ini
        args: [--autofix]
    -   id: pretty-format-toml
        args: [--autofix]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0  # Use the ref you want to point at
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore

-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort

-   repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
    -   id: black

-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args: ['--expand-star-imports', '--ignore-init-module-imports', '--in-place']

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: &flake8_dependencies
        - flake8-bugbear==21.11.29
        - flake8-builtins==1.5.3
        - flake8-comprehensions==3.7.0
        - flake8-return==1.1.3
        - flake8-simplify==0.14.2

-   repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
    -   id: yesqa
        additional_dependencies: *flake8_dependencies

# TODO setup mypy
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v0.910'
#    hooks:
#    -   id: mypy
#        pass_filenames: false
#        additional_dependencies:

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.1
    hooks:
    -   id: shellcheck
        exclude: "^pointnav_comparison"
